"""Add purga_records table.

Revision ID: 0466b869c689
Revises: 9d2924fb47a6
Create Date: 2026-02-17 17:05:04.707449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0466b869c689"
down_revision: str | Sequence[str] | None = "9d2924fb47a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purga_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("purga_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("initiated_by", sa.BigInteger(), nullable=False),
        sa.Column("mod_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("mod_message_id", sa.BigInteger(), nullable=True),
        sa.Column("user_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("user_message_id", sa.BigInteger(), nullable=True),
        sa.Column("authorized_by", sa.JSON(), nullable=False),
        sa.Column("confirmed_by", sa.JSON(), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("execution_result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purga_records", schema=None) as batch_op:
        batch_op.create_index("ix_purga_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_purga_guild_id", ["guild_id"], unique=False)
        batch_op.create_index("ix_purga_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purga_records", schema=None) as batch_op:
        batch_op.drop_index("ix_purga_status")
        batch_op.drop_index("ix_purga_guild_id")
        batch_op.drop_index("ix_purga_created_at")

    op.drop_table("purga_records")
    # ### end Alembic commands ###
