"""Initial schema.

Revision ID: 7d4d04118780
Revises:
Create Date: 2026-02-14 09:28:57.421268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "7d4d04118780"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    if not table_exists("guild_cogs_enabled"):
        op.create_table(
            "guild_cogs_enabled",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("cog_name", sa.String(length=100), nullable=False),
            sa.Column("enabled", sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("guild_id", "cog_name", name="uq_guild_cog_enabled"),
        )
        with op.batch_alter_table("guild_cogs_enabled", schema=None) as batch_op:
            batch_op.create_index("ix_guild_cog_enabled_cog_name", ["cog_name"], unique=False)
            batch_op.create_index("ix_guild_cog_enabled_guild_id", ["guild_id"], unique=False)

    if not table_exists("guild_configs"):
        op.create_table(
            "guild_configs",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("cog_name", sa.String(length=100), nullable=False),
            sa.Column("key", sa.String(length=100), nullable=False),
            sa.Column("value", sa.JSON(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("guild_id", "cog_name", "key", name="uq_guild_cog_key"),
        )
        with op.batch_alter_table("guild_configs", schema=None) as batch_op:
            batch_op.create_index("ix_guild_config_cog_name", ["cog_name"], unique=False)
            batch_op.create_index("ix_guild_config_guild_id", ["guild_id"], unique=False)

    if not table_exists("guilds"):
        op.create_table(
            "guilds",
            sa.Column("id", sa.BigInteger(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("prefix", sa.String(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    if not table_exists("verification_requests"):
        op.create_table(
            "verification_requests",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("user_id", sa.BigInteger(), nullable=False),
            sa.Column("username", sa.String(length=100), nullable=False),
            sa.Column("verification_type", sa.String(length=20), nullable=False),
            sa.Column("status", sa.String(length=30), nullable=False),
            sa.Column("screenshot_1_url", sa.Text(), nullable=True),
            sa.Column("screenshot_2_url", sa.Text(), nullable=True),
            sa.Column("reviewed_by_id", sa.BigInteger(), nullable=True),
            sa.Column("reviewed_by_username", sa.String(length=100), nullable=True),
            sa.Column("rejection_reason", sa.Text(), nullable=True),
            sa.Column("mod_message_id", sa.BigInteger(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("screenshots_submitted_at", sa.DateTime(), nullable=True),
            sa.Column("reviewed_at", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("verification_requests", schema=None) as batch_op:
            batch_op.create_index("ix_verification_guild_id", ["guild_id"], unique=False)
            batch_op.create_index("ix_verification_status", ["status"], unique=False)
            batch_op.create_index("ix_verification_user_id", ["user_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verification_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_verification_user_id")
        batch_op.drop_index("ix_verification_status")
        batch_op.drop_index("ix_verification_guild_id")

    op.drop_table("verification_requests")
    op.drop_table("guilds")
    with op.batch_alter_table("guild_configs", schema=None) as batch_op:
        batch_op.drop_index("ix_guild_config_guild_id")
        batch_op.drop_index("ix_guild_config_cog_name")

    op.drop_table("guild_configs")
    with op.batch_alter_table("guild_cogs_enabled", schema=None) as batch_op:
        batch_op.drop_index("ix_guild_cog_enabled_guild_id")
        batch_op.drop_index("ix_guild_cog_enabled_cog_name")

    op.drop_table("guild_cogs_enabled")
    # ### end Alembic commands ###
