"""Add invited_by_id to guilds.

Revision ID: 9d2924fb47a6
Revises: e8d46a4c1578
Create Date: 2026-02-15 21:37:57.393791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d2924fb47a6"
down_revision: str | Sequence[str] | None = "e8d46a4c1578"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guilds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("invited_by_id", sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guilds", schema=None) as batch_op:
        batch_op.drop_column("invited_by_id")

    # ### end Alembic commands ###
